### ISSUE TITLE
staticfiles error

### ISSUE THREAD

**Issue by cyberbudy** [demiroren-teknoloji/django-admin-autocomplete-list-filter#4]
django admin raises exception `'staticfiles' is not a registered tag library`, because the staticfiles and admin_static template tag libraries are removed in 3.0.
There is a PR https://github.com/demiroren-teknoloji/django-admin-autocomplete-list-filter/pull/3
that is not accepted

**Comment by canadiyaman** [comment]
@vigo can you check it?

**Comment by vigo** [comment]
@canadiyaman will check soon

**Comment by skanel** [comment]
I made it work by override the template and removed `staticfiles ` by just `static`
 the content of file `autocomplete_list_filter.html` will like this

`/YOUR_PROJECT_DJANGO/templates/djaa_list_filter/admin/filter/autocomplete_list_filter.html`

```
{% load  static %}

<form method="get">
<ul>
    <li>{{ spec.autocomplete_form.autocomplete_field }}</li>
</ul>
{{ spec.autocomplete_form.querystring_value }}
</form>
```

**Comment by vigo** [comment]
Just gained write access, will handle asap

**Comment by vigo** [comment]
Fixed now! thanks
